#!/bin/sh /etc/rc.common

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/sshd
DROPBEAR_BIN="/mnt/SDCARD/System/bin/dropbear"

start_service() {

    # --- CrossMix : dropbear ---
    if [ -x "$DROPBEAR_BIN" ]; then
        killall $PROG 2>/dev/null
        nice -2 "$DROPBEAR_BIN" -R &

        start=$(date +%s)
        sleep 1
        end=$(date +%s)
        duration=$((end - start))

        if [ "$duration" -ge 1 ]; then # The SSH checkbox was just enabled; trick: when MainUI starts, the 'sleep' command is ignored.

            IP=$(ip route get 1 2>/dev/null | awk '{print $NF;exit}')
            echo -e "{ \"type\":\"info\" , \"duration\":5000, \"x\":340, \"y\":550, \"size\":2, \"message\":\"IP address: $IP\", \"font\":\"\", \"icon\":\"\", \"fontsize\":24 }" >/tmp/trimui_osd/osd_toast_msg

            # Reflect change on System Tools
            "/mnt/SDCARD/Apps/SystemTools/Menu/NETWORK##SSH (state)/SSH Server  - enable.sh" -s &
        fi

        return

    fi

    # --- Stock: sshd ---
    for type in rsa ecdsa ed25519; do
        key=/etc/ssh/ssh_host_${type}_key
        [ ! -f $key ] && {
            [ -x /usr/bin/ssh-keygen ] && {
                /usr/bin/ssh-keygen -N '' -t $type -f $key 2>&- >&-
            }
        }
    done

    mkdir -m 0700 -p /var/empty

    local lport=$(awk '/^Port / { print $2; exit }' /etc/ssh/sshd_config)
    [ -z "$lport" ] && lport=22

    procd_open_instance
    procd_add_mdns "ssh" "tcp" "$lport"
    procd_set_param command $PROG -D
    procd_close_instance
}

stop_service() {
    echo "Stopping SSH service (sshd or dropbear)..."

    if pgrep $PROG >/dev/null 2>&1; then
        echo "Killing sshd..."
        killall $PROG 2>/dev/null
    fi

    if pgrep "$DROPBEAR_BIN" >/dev/null 2>&1; then
        echo "Killing dropbear..."
        killall "$DROPBEAR_BIN" 2>/dev/null
    fi

    # --- CrossMix ---
    if [ -x "$DROPBEAR_BIN" ]; then
        "/mnt/SDCARD/Apps/SystemTools/Menu/NETWORK##SSH (state)/SSH Server - disable.sh" -s
    fi
}

shutdown() {
    local pid

    stop

    # kill active clients (mode sshd)
    for pid in $(pidof sshd); do
        [ "$pid" == "$$" ] && continue
        [ -e "/proc/$pid/stat" ] && kill $pid
    done
}
